// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package UserStore

import (
	"fmt"
	"github.com/aliabdullahcp/evernote-golang-sdk/Errors"
	"github.com/aliabdullahcp/evernote-golang-sdk/Types"
	"github.com/apache/thrift/lib/go/thrift"
	"math"
)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

var _ = Types.GoUnusedProtection__
var _ = Errors.GoUnusedProtection__

const EDAM_VERSION_MAJOR = 1
const EDAM_VERSION_MINOR = 25

func init() {
}
